# Job that will download the other artifact from the build and will add a comment with the contents.
parameters:

- name: isPR
  type: boolean

- name: repositoryAlias
  type: string
  default: self

- name: commit
  type: string
  default: HEAD

steps:

- template: ../common/checkout.yml
  parameters:
    isPR: ${{ parameters.isPR }}
    repositoryAlias: ${{ parameters.repositoryAlias }}
    commit: ${{ parameters.commit }}

- template: ../build/download-artifacts.yml 
  parameters:
    runTests: false  # we do not run tests on builds
    enableAPIDiff: false  # we do not run the api diff here.

- pwsh: |
    Import-Module $Env:SYSTEM_DEFAULTWORKINGDIRECTORY\xamarin-macios\tools\devops\automation\scripts\MaciosCI.psd1
    $artifact = New-ArtifactsFromJsonFile -Path "$Env:ARTIFACTS_JSON_PATH"
    $gihubComments = New-GitHubCommentsObjectFromUrl -Url "$(Build.Repository.Uri)" -Token $Env:GITHUB_TOKEN -Hash $Env:COMMENT_HASH
    $result = $gihubComments.NewCommentFromObject("Artifacts", ":books:", $artifact)
    Write-Host $result
  env:
    GITHUB_TOKEN: $(GitHub.Token)
    ACCESSTOKEN: $(System.AccessToken)
    ${{ if eq(parameters.repositoryAlias, 'self') }}:
      COMMENT_HASH: $(GIT_HASH)
    ${{ else }}:
      COMMENT_HASH: $(Build.SourceVersion)
  displayName: 'Create github comment.'
  enabled: true
  timeoutInMinutes: 10
