# Perform gihub cleaning steps

parameters:
- name: commentToHide
  type: string
  default: '[comment]: <> (This is a comment added by Azure DevOps)'

- name: checkoutCode
  type: boolean
  default: true

- name: repositoryAlias
  type: string
  default: self

- name: commit
  type: string
  default: HEAD

steps:

- ${{ if parameters.checkoutCode }}:
  - template: checkout.yml
    parameters:
      isPR: false # always use the latests version of the script
      repositoryAlias: ${{ parameters.repositoryAlias }}
      commit: ${{ parameters.commit }}

- pwsh: >-
    ./clean_past_comments.ps1
    -GithubToken "$(GitHub.Token)"
    -RepositoryUri "$(Build.Repository.Uri)"
    -SourceBranch "$(Build.SourceBranch)"
    -CommentToHide "${{ parameters.commentToHide }}"
  displayName: Clear past comments
  workingDirectory: $(System.DefaultWorkingDirectory)/xamarin-macios/tools/devops/automation/scripts
