# This templates allows to set a status on github. Takes the following paramenters:

parameters: 

- name: githubToken
  type: string

- name: status
  type: string
  values:
  - error
  - failure
  - pending
  - success

- name: description
  type: string

- name: context
  type: string

- name: targetUrl
  type: string
  default: ''

- name: displayName
  type: string
  default: 'Set GitHub status'

- name: continueOnError
  default: true

- name: condition
  default: true

- name: timeoutInMinutes
  default: 5

steps:

- pwsh: |
    Import-Module .\\MaciosCI.psd1
    # calcualte the repo we are using, rather than using a parameter, we can use the URI from github, for example: https://github.com/xamarin/sdk-insertions

    $statuses = New-GitHubStatusesObjectFromUrl -Url "$(Build.Repository.Uri)" -Token "${{ parameters.githubToken }}"
    $statuses.SetStatus("${{ parameters.status }}", "${{ parameters.description }}", "${{ parameters.context }}", "${{ parameters.targetUrl }}")
  displayName: ${{ parameters.displayName }}
  workingDirectory: $(System.DefaultWorkingDirectory)/xamarin-macios/tools/devops/automation/scripts
  continueOnError: ${{ parameters.continueOnError }}
  condition: ${{ parameters.condition }}
  timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
