name: Get Localization Translations
on:
  push:
    branches:
    - "lego/*"

permissions:
  contents: read

jobs:
  pull-request:
    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: write  # for repo-sync/pull-request to create pull requests
    name: '[Localization PR to main]'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: checkout

    - uses: repo-sync/pull-request@v2
      name: pull-request
      with:
        destination_branch: "main"
        pr_title: "[Localization] Pulling New Localization Translations $GITHUB_RUN_ID"
        pr_body: "Automated PR. Bring new translated changes in the lcl files for OneLocBuild to create translated resx files."
        pr_label: "localization_bot,not-notes-worthy"
        pr_milestone: "Future"
        pr_allow_empty: false
        github_token: ${{ secrets.GITHUB_TOKEN }}
